/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proje11;

import java.util.ArrayList;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author WIN-7 PC
 */
public class PersonelDüzenleme extends javax.swing.JFrame {

    /**
     * Creates new form PersonelDüzenleme
     */
    
    ArrayList<Personel> personellistYedek =new ArrayList();
    DefaultComboBoxModel<Object> dcmb=new DefaultComboBoxModel<>();
   
    public PersonelDüzenleme(){
        initComponents();
    }
    public PersonelDüzenleme(ArrayList<Personel> pList) {
        initComponents();
        
        for (Object b : Birim.birimler) {
            dcmb.addElement(b);
        }
        jComboBoxBirimler.setModel(dcmb);
        
        for (Personel p : pList) {
            personellistYedek.add(p);
        }
        hataAd.setVisible(false);
        hataSoyad.setVisible(false);
        hataId.setVisible(false);
        hataMaas.setVisible(false);
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtsoyad1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtad = new javax.swing.JTextField();
        txtsoyad = new javax.swing.JTextField();
        jComboBoxBirimler = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        btnEkle = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnEkle1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtmaas = new javax.swing.JTextField();
        hataMaas = new javax.swing.JLabel();
        hataAd = new javax.swing.JLabel();
        hataSoyad = new javax.swing.JLabel();
        hataId = new javax.swing.JLabel();

        txtsoyad1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel8.setForeground(new java.awt.Color(204, 0, 0));
        jLabel8.setText("(Lütfen gecerli bir isim giriniz)");

        jLabel10.setForeground(new java.awt.Color(204, 0, 0));
        jLabel10.setText("(Lütfen gecerli bir isim giriniz)");

        jLabel12.setForeground(new java.awt.Color(204, 0, 0));
        jLabel12.setText("(Lütfen gecerli bir isim giriniz)");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setText("Ad:");

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setText("Soyad:");

        txtad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtadActionPerformed(evt);
            }
        });

        txtsoyad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jComboBoxBirimler.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jComboBoxBirimler.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBirimler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxBirimlerActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setText("Birim:");

        btnEkle.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEkle.setText("Kişiyi Kaydet");
        btnEkle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkleActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Pazartesi");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jCheckBox2.setText("Salı");

        jCheckBox3.setText("Carsamba");

        jCheckBox4.setText("Persembe");

        jCheckBox5.setText("Cuma");

        jCheckBox6.setText("Cumartesi");

        jCheckBox7.setText("Pazar");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setText("İzin:");

        btnEkle1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnEkle1.setText("Iptal");
        btnEkle1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEkle1ActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setText("Id:");

        txtId.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setText("Maas:");

        txtmaas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        hataMaas.setForeground(new java.awt.Color(204, 0, 0));
        hataMaas.setText("*Hatalı değer girdiniz.");

        hataAd.setForeground(new java.awt.Color(204, 0, 0));
        hataAd.setText("*Hatalı ad girdiniz.");

        hataSoyad.setForeground(new java.awt.Color(204, 0, 0));
        hataSoyad.setText("*Hatalı soyad girdiniz.");

        hataId.setForeground(new java.awt.Color(204, 0, 0));
        hataId.setText("*Hatalı değer girdiniz.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(hataId, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(txtmaas)
                            .addComponent(txtad, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                            .addComponent(txtsoyad, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(hataMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hataAd, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(hataSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jComboBoxBirimler, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox4)
                                    .addComponent(jCheckBox1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox2)
                                    .addComponent(jCheckBox5))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCheckBox3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jCheckBox6, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addComponent(jCheckBox7)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(hataAd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsoyad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(hataSoyad, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtmaas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(hataMaas, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(hataId, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxBirimler, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox1)
                                .addComponent(jCheckBox2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox4)
                                .addComponent(jCheckBox5)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jCheckBox3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox6)
                                .addComponent(jCheckBox7)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEkle, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEkle1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxBirimlerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxBirimlerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxBirimlerActionPerformed
Yonetim y;
    boolean idKontrol(int id){
        
        boolean idGecerli=true;
        for (Personel p : personellistYedek) {
            if (p.id==id) {
                idGecerli=false;
            }
        }
    
    
    return idGecerli;
    }
    private void btnEkleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkleActionPerformed
        // TODO add your handling code here: 
        boolean ekleme=true;
        if (desenKontrol("[^A-z]", txtad.getText())|| txtad.getText().isEmpty()) {
            hataAd.setVisible(true);
            ekleme=false;
        } else {
            hataAd.setVisible(false);
            
        }
        if (desenKontrol("[^A-z]", txtsoyad.getText()) || txtsoyad.getText().isEmpty())  {
            hataSoyad.setVisible(true);
            ekleme=false;
        } else {
            hataSoyad.setVisible(false);
            
        } 
        if (desenKontrol("[^0-9]", txtmaas.getText()) || txtmaas.getText().isEmpty() || Integer.parseInt(txtmaas.getText())<=0) {
            hataMaas.setVisible(true);
            ekleme=false;
             
        } 
        else {
            hataMaas.setVisible(false);
        } 
        if (desenKontrol("[^0-9]", txtId.getText()) || txtId.getText().isEmpty() || Integer.parseInt(txtId.getText())<0) {
            hataId.setVisible(true);
            ekleme=false;
            
        } else {
            
            hataId.setVisible(false);
        }
        if (desenKontrol("[^0-9]", txtId.getText()) ==false)  {
            if (idKontrol(Integer.parseInt(txtId.getText())) ==false)  {
                JOptionPane.showMessageDialog(rootPane,"Personel id mevcut ya da eksik.", "Hatalı Islem", WIDTH);
            ekleme=false;
            }
            
        }
       
        if (ekleme) {
            personelEkleme();
        }
        
        
          
        
         
         
        
        
    }//GEN-LAST:event_btnEkleActionPerformed

    private void btnEkle1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEkle1ActionPerformed
        // TODO add your handling code here:
        new Yonetim(personellistYedek).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnEkle1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
    }//GEN-LAST:event_jCheckBox1ActionPerformed
     boolean desenKontrol(String desenMetni, String arananMetin) {

        Pattern desen = Pattern.compile(desenMetni);
        Matcher m = desen.matcher(arananMetin);
        return m.find();

    }
     public void personelEkleme(){
     Personel p =new Personel();
         p.ad=txtad.getText();
         p.soyad=txtsoyad.getText();       
         p.birimadı=(jComboBoxBirimler.getSelectedItem().toString());
         p.id=(Integer.parseInt(txtId.getText()));
         p.maasMiktar=Integer.parseInt(txtmaas.getText());
        
         if (jCheckBox1.isSelected()) {
            p.izinGünleri.add(jCheckBox1.getText());
        }
         if (jCheckBox2.isSelected()) {
            p.izinGünleri.add(jCheckBox2.getText());
        }
         if (jCheckBox3.isSelected()) {
            p.izinGünleri.add(jCheckBox3.getText());
        }
         if (jCheckBox4.isSelected()) {
            p.izinGünleri.add(jCheckBox4.getText());
        }
         if (jCheckBox5.isSelected()) {
            p.izinGünleri.add(jCheckBox5.getText());
        }
         if (jCheckBox6.isSelected()) {
            p.izinGünleri.add(jCheckBox6.getText());
        }
         if (jCheckBox7.isSelected()) {
            p.izinGünleri.add(jCheckBox7.getText());
        }
           personellistYedek.add(p);
            y = new Yonetim(personellistYedek);
         
         y.setVisible(true);
         this.dispose();
        
     }
    
    private void txtadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonelDüzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonelDüzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonelDüzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonelDüzenleme.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonelDüzenleme().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEkle;
    private javax.swing.JButton btnEkle1;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel hataAd;
    private javax.swing.JLabel hataId;
    private javax.swing.JLabel hataMaas;
    private javax.swing.JLabel hataSoyad;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JComboBox jComboBoxBirimler;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtad;
    private javax.swing.JTextField txtmaas;
    private javax.swing.JTextField txtsoyad;
    private javax.swing.JTextField txtsoyad1;
    // End of variables declaration//GEN-END:variables
}
